# Generated by Django 5.0.6 on 2024-05-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('פעיל', 'active'), ('לא פעיל', 'off'), ('בחופשה', 'on_leave'), ('נא לבחור', 'choose')], default='נא לבחור', max_length=30, verbose_name='status'),
        ),
    ]
