# Generated by Django 5.0.6 on 2024-05-22 01:46

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=users.models.CustomMultiSelectField(blank=True, choices=[('bar', 'בר'), ('waiter', 'מלצר\\ית'), ('hot_streak', 'פס חם'), ('cold_streak', 'פס קר'), ('manager', 'אחמ"ש'), ('director', 'מנהל'), ('checker', "צ'קר"), ('cleanliness', 'ניקיון'), ('hostess', 'הוסטס'), ('hostess', 'מארחת')], max_length=250, verbose_name='roles'),
        ),
    ]
