# Generated by Django 5.0.6 on 2024-05-21 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('role', models.CharField(max_length=50, verbose_name='role')),
                ('workday', models.CharField(blank=True, choices=[('working_day', 'יום עבודה'), ('day_off', 'יום חופש')], max_length=30, null=True, verbose_name='is_work_day')),
                ('shift', models.CharField(choices=[('morning', 'בוקר'), ('evening', 'עֶרֶב')], max_length=30, verbose_name='shift')),
            ],
            options={
                'verbose_name': 'Product list',
                'verbose_name_plural': 'Product list',
            },
        ),
        migrations.CreateModel(
            name='TaskListShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('role', models.CharField(max_length=50, verbose_name='role')),
                ('workday', models.CharField(blank=True, choices=[('working_day', 'יום עבודה'), ('day_off', 'יום חופש')], max_length=30, null=True, verbose_name='is_work_day')),
                ('shift', models.CharField(choices=[('morning', 'בוקר'), ('evening', 'עֶרֶב')], max_length=30, verbose_name='shift')),
            ],
            options={
                'verbose_name': 'Task list',
                'verbose_name_plural': 'Task list',
            },
        ),
        migrations.CreateModel(
            name='TemplateProductListShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('role', models.CharField(max_length=50, verbose_name='role')),
                ('workday', models.CharField(blank=True, choices=[('working_day', 'יום עבודה'), ('day_off', 'יום חופש')], max_length=30, null=True, verbose_name='is_work_day')),
                ('shift', models.CharField(choices=[('morning', 'בוקר'), ('evening', 'עֶרֶב')], max_length=30, verbose_name='shift')),
            ],
            options={
                'verbose_name': 'Product template',
                'verbose_name_plural': 'Product templates',
            },
        ),
        migrations.CreateModel(
            name='TemplateTaskListShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('role', models.CharField(max_length=50, verbose_name='role')),
                ('workday', models.CharField(blank=True, choices=[('working_day', 'יום עבודה'), ('day_off', 'יום חופש')], max_length=30, null=True, verbose_name='is_work_day')),
                ('shift', models.CharField(choices=[('morning', 'בוקר'), ('evening', 'עֶרֶב')], max_length=30, verbose_name='shift')),
            ],
            options={
                'verbose_name': 'Task template',
                'verbose_name_plural': 'Task templates',
            },
        ),
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenItemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(blank=True, null=True, verbose_name='משימה')),
                ('arabic_name', models.TextField(blank=True, null=True, verbose_name='שם בערבית')),
                ('short', models.IntegerField(default=0, verbose_name='חסר')),
                ('standard', models.IntegerField(default=0, verbose_name='תקן')),
                ('morning', models.IntegerField(default=0, verbose_name='בוקר')),
                ('evening', models.IntegerField(default=0, verbose_name='ערב')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='סיבה')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_list', to='checklist.productlistshift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoleItemTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='משימה')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='שעה')),
                ('status', models.CharField(choices=[('done', 'בוצע'), ('not_done', 'לא בוצע'), ('choose', 'נא לבחור')], max_length=40, verbose_name='סטטוס')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_list', to='checklist.tasklistshift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KitchenItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(blank=True, null=True, verbose_name='משימה')),
                ('arabic_name', models.TextField(blank=True, null=True, verbose_name='שם בערבית')),
                ('short', models.IntegerField(default=0, verbose_name='חסר')),
                ('standard', models.IntegerField(default=0, verbose_name='תקן')),
                ('morning', models.IntegerField(default=0, verbose_name='בוקר')),
                ('evening', models.IntegerField(default=0, verbose_name='ערב')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='סיבה')),
                ('template_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_item', to='checklist.templateproductlistshift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoleItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='משימה')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='שעה')),
                ('status', models.CharField(choices=[('done', 'בוצע'), ('not_done', 'לא בוצע'), ('choose', 'נא לבחור')], max_length=40, verbose_name='סטטוס')),
                ('template_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_item', to='checklist.templatetasklistshift')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='templatetasklistshift',
            name='working_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_task_list', to='checklist.workingshift'),
        ),
        migrations.AddField(
            model_name='templateproductlistshift',
            name='working_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_product_list', to='checklist.workingshift'),
        ),
        migrations.AddField(
            model_name='tasklistshift',
            name='working_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_list', to='checklist.workingshift'),
        ),
        migrations.AddField(
            model_name='productlistshift',
            name='working_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='checklist.workingshift'),
        ),
    ]
