# Generated by Django 5.0.6 on 2024-05-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holeitemtask',
            name='status',
            field=models.CharField(choices=[('בוצע', 'done'), ('לא בוצע', 'not_done'), ('נא לבחור', 'choose')], max_length=40, verbose_name='סטטוס'),
        ),
        migrations.AlterField(
            model_name='holeitemtemplate',
            name='status',
            field=models.CharField(choices=[('בוצע', 'done'), ('לא בוצע', 'not_done'), ('נא לבחור', 'choose')], max_length=40, verbose_name='סטטוס'),
        ),
        migrations.AlterField(
            model_name='productlistshift',
            name='shift',
            field=models.CharField(choices=[('בוקר', 'morning'), ('עֶרֶב', 'evening')], max_length=30, verbose_name='shift'),
        ),
        migrations.AlterField(
            model_name='productlistshift',
            name='workday',
            field=models.CharField(blank=True, choices=[('יום עבודה', 'working_day'), ('יום חופש', 'day_off')], max_length=30, null=True, verbose_name='is_work_day'),
        ),
        migrations.AlterField(
            model_name='tasklistshift',
            name='shift',
            field=models.CharField(choices=[('בוקר', 'morning'), ('עֶרֶב', 'evening')], max_length=30, verbose_name='shift'),
        ),
        migrations.AlterField(
            model_name='tasklistshift',
            name='workday',
            field=models.CharField(blank=True, choices=[('יום עבודה', 'working_day'), ('יום חופש', 'day_off')], max_length=30, null=True, verbose_name='is_work_day'),
        ),
        migrations.AlterField(
            model_name='templateproductlistshift',
            name='shift',
            field=models.CharField(choices=[('בוקר', 'morning'), ('עֶרֶב', 'evening')], max_length=30, verbose_name='shift'),
        ),
        migrations.AlterField(
            model_name='templateproductlistshift',
            name='workday',
            field=models.CharField(blank=True, choices=[('יום עבודה', 'working_day'), ('יום חופש', 'day_off')], max_length=30, null=True, verbose_name='is_work_day'),
        ),
        migrations.AlterField(
            model_name='templatetasklistshift',
            name='shift',
            field=models.CharField(choices=[('בוקר', 'morning'), ('עֶרֶב', 'evening')], max_length=30, verbose_name='shift'),
        ),
        migrations.AlterField(
            model_name='templatetasklistshift',
            name='workday',
            field=models.CharField(blank=True, choices=[('יום עבודה', 'working_day'), ('יום חופש', 'day_off')], max_length=30, null=True, verbose_name='is_work_day'),
        ),
    ]
