# Generated by Django 5.0.6 on 2024-05-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_productlistshift_is_active_tasklistshift_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holeitemtask',
            name='is_dyn',
            field=models.BooleanField(default=False, verbose_name='is_dyn_task'),
        ),
    ]
