# Generated by Django 5.0.6 on 2024-05-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_holeitemtask_is_dyn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistshift',
            name='role',
            field=models.CharField(choices=[('bar', 'בר'), ('waiter', 'מלצר\\ית'), ('hot_streak', 'פס חם'), ('cold_streak', 'פס קר'), ('manager', 'אחמ"ש'), ('director', 'מנהל'), ('checker', "צ'קר"), ('cleanliness', 'ניקיון'), ('hostess', 'הוסטס'), ('hostess', 'מארחת')], max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='tasklistshift',
            name='role',
            field=models.CharField(choices=[('bar', 'בר'), ('waiter', 'מלצר\\ית'), ('hot_streak', 'פס חם'), ('cold_streak', 'פס קר'), ('manager', 'אחמ"ש'), ('director', 'מנהל'), ('checker', "צ'קר"), ('cleanliness', 'ניקיון'), ('hostess', 'הוסטס'), ('hostess', 'מארחת')], max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='templateproductlistshift',
            name='role',
            field=models.CharField(choices=[('bar', 'בר'), ('waiter', 'מלצר\\ית'), ('hot_streak', 'פס חם'), ('cold_streak', 'פס קר'), ('manager', 'אחמ"ש'), ('director', 'מנהל'), ('checker', "צ'קר"), ('cleanliness', 'ניקיון'), ('hostess', 'הוסטס'), ('hostess', 'מארחת')], max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='templatetasklistshift',
            name='role',
            field=models.CharField(choices=[('bar', 'בר'), ('waiter', 'מלצר\\ית'), ('hot_streak', 'פס חם'), ('cold_streak', 'פס קר'), ('manager', 'אחמ"ש'), ('director', 'מנהל'), ('checker', "צ'קר"), ('cleanliness', 'ניקיון'), ('hostess', 'הוסטס'), ('hostess', 'מארחת')], max_length=50, verbose_name='role'),
        ),
    ]
