# Generated by Django 5.0.6 on 2024-05-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_holeitemtask_comment_holeitemtemplate_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holeitemtask',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='למה לא בוצע'),
        ),
        migrations.AlterField(
            model_name='holeitemtemplate',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='למה לא בוצע'),
        ),
    ]
