# Generated by Django 5.0.6 on 2024-05-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_alter_holeitemtask_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenitemproduct',
            name='status',
            field=models.CharField(choices=[('done', 'בוצע'), ('not_done', 'לא בוצע'), ('choose', 'נא לבחור')], default='choose', max_length=40, verbose_name='סטטוס'),
        ),
    ]
